version: '3'

services:
  app:
    build: 
      dockerfile: app/Dockerfile
      context: .
    environment:
      FLAG: ptm{fake_flag}
      AUTH_ADDR: auth:8081
      GIN_MODE: release
    ports:
      - 8080:8080
    restart: unless-stopped
  auth:
    build: 
      dockerfile: auth/Dockerfile
      context: .
    environment:
      GIN_MODE: release
    restart: unless-stopped